### ISSUE TITLE
Why mix repository and mapper ?

### ISSUE THREAD

**Issue by kazuki43zoo** [terasoluna-batch/v5-fw#1]
## Description
In current implementation of `BatchJobRequestMapper`, 

* class name suffix is `Mapper`
* belong package name is `repository`

Why mix repository and mapper ? 
I think it is confusing for user(developer).
 
## Possible Solutions

* Change to package name to `mapper`
* Change to class name suffix to `Repository`

## Affects Version/s
* 5.0.0.RELEASE

## Fix Version/s
(To be written later by project member)

## Issue Links
* #XXX

**Comment by hosoitk** [comment]
Thank you for your advice.
We changed class name suffix to `Repository` in `Tag: 5.0.1.RELEASE`.
