### ISSUE TITLE
Upgrade to MyBatis 3.4.6

### ISSUE THREAD

**Issue by kazuki43zoo** [terasoluna-batch/v5-fw#10]
## Description

The [MyBatis 3.4.6](http://blog.mybatis.org/2018/03/mybatis-346-released.html) has been released.

## Possible Solutions
(Please write ideas or candidates of solutions for the problem if you have)

## Affects Version/s
* 5.X.X.RELEASE

## Fix Version/s
(To be written later by project member)

## Issue Links
* #XXX

**Comment by yggd** [comment]
Updated to MyBatis 3.4.6 in TERASOLIUNA Batch 5.2.0 / 5.1.2.
