### ISSUE TITLE
Upgrade to MyBatis-Spring 1.3.2

### ISSUE THREAD

**Issue by kazuki43zoo** [terasoluna-batch/v5-fw#11]
## Description
The [MyBatis-Spring 1.3.2](http://blog.mybatis.org/2018/03/mybatis-spring-132-released.html) has been released.

> **NOTE:**
> In this version, the `MyBatisCursorItemReader`'s bug is fixed.
> When this change will be applied, you can remove the warning for ["MyBatisCursorItemReaderにおけるクローズ時の注意事項について"](https://terasoluna-batch.github.io/guideline/5.1.1.RELEASE/ja/Ch05_DBAccess.html#Ch05_DBAccess_HowToUse_Input_MyBatisItemReader) in the guideline.

## Possible Solutions
(Please write ideas or candidates of solutions for the problem if you have)

## Affects Version/s
* 5.X.X.RELEASE

## Fix Version/s
(To be written later by project member)

## Issue Links
* #XXX

**Comment by yggd** [comment]
Updated to MyBatis-Spring 1.3.2 in TERASOLIUNA Batch 5.2.0 / 5.1.2.
