### ISSUE TITLE
Suggest to improve a log message of AsyncBatchDaemon on error time 

### ISSUE THREAD

**Issue by kazuki43zoo** [terasoluna-batch/v5-fw#5]
## Description

Currently, it is as follow:

```
Daemon termination error: ${exception message}
```

It is not same format with other message at start/stop time. 

e.g. ) at startup time

```
Async Batch Daemon start.
```

e.g.) at normal stopped time

```
Async Batch Daemon stopped after all jobs completed.
```

## Possible Solutions

I think as following log message is better.

e.g.)

```
Async Batch Daemon stopped due to an error. [Error:${exception message}]
```

What do you think ?

## Affects Version/s
* 5.0.0.RELEASE

## Fix Version/s
(To be written later by project member)

## Issue Links
* #XXX

**Comment by yggd** [comment]
As you pointed out, the format has been modified to be the same.
This fix is supported since 5.1.0.RELEASE.
