### ISSUE TITLE
Can stop daemon when create same name directory instead of regular atop file

### ISSUE THREAD

**Issue by kazuki43zoo** [terasoluna-batch/v5-fw#6]
## Description
I've created a directory (same name with stop file) as follow:

```
$ mkdir /tmp/end-async-batch-daemon
```

A daemon process is stopped in this case. Is this behavior working as design ? or bug ?

A cause-by of this behavior is https://github.com/terasoluna-batch/v5-fw/blob/master/terasoluna-batch/src/main/java/org/terasoluna/batch/async/db/AsyncBatchDaemon.java#L206. 

## Possible Solutions

If this behavior is bug, I think there are two options to fix this behavior.

* The `AsyncBatchDaemon` will perform a checking whether a regular file or not at watching time.
* The `AsyncBatchDaemon` will not perform a directory checking at the startup time. 

## Affects Version/s
* 5.0.0.RELEASE

## Fix Version/s
(To be written later by project member)

## Issue Links
* #XXX

**Comment by yggd** [comment]
Directory check is not considered. Fixed not to stop in directory.
This fix is supported since 5.1.0.RELEASE.
