### ISSUE TITLE
Why does not use the java.time.Clock on JobRequestPollTask

### ISSUE THREAD

**Issue by kazuki43zoo** [terasoluna-batch/v5-fw#8]
## Description
In current implementation, a system timestamp get using the `System.currentTimeMillis()`. It is not extensible.

## Possible Solutions

I suggest using the `java.time.Clock` to get a system timestamp.

e.g.)

```xml
<bean id="clock" class="java.time.Clock" factory-method="systemDefaultZone" />
```

```java
protected Timestamp getSystemTimestamp() {
   return new Timestamp(clock.millis());
}
```

What do you think ?

## Affects Version/s
* 5.0.0.RELEASE

## Fix Version/s
(To be written later by project member)

## Issue Links
* #XXX

**Comment by yggd** [comment]
Fixed to use the proposed `java.time.Clock`.
This fix is supported since 5.1.0.RELEASE.
