### ISSUE TITLE
mybatis 3.4.5 include same classes with mybatis-typehandlers-jsr310

### ISSUE THREAD

**Issue by kazuki43zoo** [terasoluna-batch/v5-fw#9]
## Description
See https://github.com/mybatis/mybatis-3/pull/974.

## Possible Solutions
Remove the dependency definition for mybatis-typehandlers-jsr310.

## Affects Version/s
* 5.1.0.RELEASE +

## Fix Version/s
(To be written later by project member)

## Issue Links
* #XXX

**Comment by yggd** [comment]
We Removed the definition from dependencies.
This is supported since 5.3.0.RELEASE and 5.2.1.RELEASE.
